- hosts: localhost
  become: true
  tasks:

    - name: Install OpenSSH
      pacman:
        name: openssh
        state: present

    - name: Enable and start SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Allow SSH in firewall (if UFW is used)
      command: ufw allow 22/tcp
      ignore_errors: yes
