- hosts: localhost
  become: true
  tasks:

    - name: Update system and upgrade all packages
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install Xorg (Display Server)
      pacman:
        name:
          - xorg
          - xorg-server
        state: present

    - name: Install Nvidia Drivers (Using DKMS)
      pacman:
        name:
          - nvidia-dkms
          - nvidia-utils
          - lib32-nvidia-utils  # For Steam & 32-bit apps
          - nvidia-settings      # Nvidia control panel
          - nvidia-prime         # For hybrid graphics (if needed)
        state: present

    - name: Remove kms from mkinitcpio hooks
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '(^HOOKS=.*)\bkms\b'
        replace: '\1'
      notify: Regenerate Initramfs

    - name: Enable Nvidia DRM Kernel Mode Setting
      copy:
        dest: /etc/modprobe.d/nvidia-drm.conf
        content: "options nvidia-drm modeset=1"

    - name: Regenerate Initramfs
      command: mkinitcpio -P

    - name: Install KDE Plasma
      pacman:
        name:
          - plasma
          - kde-applications
        state: present

    - name: Install SDDM (KDE Display Manager)
      pacman:
        name: sddm
        state: present

    - name: Force SDDM to use X11
      copy:
        dest: /etc/sddm.conf.d/kde_settings.conf
        content: |
          [General]
          DisplayServer=x11

    - name: Set ibt=off in GRUB for 11th Gen+ Intel CPUs
      replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"'
        replace: '\1 ibt=off"'
      notify: Update GRUB

    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg

    - name: Enable SDDM to start at boot
      systemd:
        name: sddm
        enabled: yes
        state: started

  handlers:
    - name: Regenerate Initramfs
      command: mkinitcpio -P
    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
