- hosts: localhost
  become: true
  tasks:

    - name: Install Networking Tools (dhcpcd, systemd-networkd, systemd-resolved, OpenSSH)
      pacman:
        name:
          - dhcpcd
          - openssh
        state: present

    - name: Enable and start dhcpcd (DHCP client)
      systemd:
        name: dhcpcd
        enabled: yes
        state: started

    - name: Enable and start systemd-networkd
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Enable and start systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Ensure DNS resolver is correctly linked
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes

    - name: Enable and start SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Allow SSH in firewall (if UFW is installed)
      command: ufw allow 22/tcp
      ignore_errors: yes
