- hosts: localhost
  become: true
  tasks:

    - name: Update system and upgrade all packages
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install Xorg (Display Server)
      pacman:
        name:
          - xorg
          - xorg-server
        state: present

    - name: Install Nvidia Drivers (Using DKMS)
      pacman:
        name:
          - nvidia-dkms
          - nvidia-utils
          - lib32-nvidia-utils  # For Steam & 32-bit apps
          - nvidia-settings      # Nvidia control panel
          - nvidia-prime         # For hybrid graphics (if needed)
        state: present

    - name: Remove kms from mkinitcpio hooks
      replace:
        path: /etc/mkinitcpio.conf
        regexp: '(^HOOKS=.*)\bkms\b'
        replace: '\1'
      notify: Regenerate Initramfs

    - name: Enable Nvidia DRM Kernel Mode Setting
      copy:
        dest: /etc/modprobe.d/nvidia-drm.conf
        content: "options nvidia-drm modeset=1"

    - name: Regenerate Initramfs
      command: mkinitcpio -P

    - name: Install KDE Plasma
      pacman:
        name:
          - plasma
          - kde-applications
        state: present

    - name: Install SDDM (KDE Display Manager)
      pacman:
        name: sddm
        state: present

    - name: Ensure SDDM config directory exists
      file:
        path: /etc/sddm.conf.d
        state: directory
        mode: '0755'

    - name: Force SDDM to use X11
      copy:
        dest: /etc/sddm.conf.d/kde_settings.conf
        content: |
          [General]
          DisplayServer=X11

    - name: Ensure Plasma X11 is the default session for all users
      copy:
        dest: /usr/share/xsessions/plasma.desktop
        content: |
          [Desktop Entry]
          Name=Plasma
          Comment=KDE Plasma
          Exec=/usr/bin/startplasma-x11
          TryExec=/usr/bin/startplasma-x11
          Type=Application

    - name: Set ibt=off in GRUB for 11th Gen+ Intel CPUs
      replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"'
        replace: '\1 ibt=off"'
      notify: Update GRUB

    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg

    - name: Enable SDDM to start at boot
      systemd:
        name: sddm
        enabled: yes
        state: started

    - name: Install OpenSSH
      pacman:
        name: openssh
        state: present

    - name: Enable and start SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Disable suspend, hibernate, hybrid-sleep & suspend-then-hibernate
      systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
      loop:
        - sleep.target
        - suspend.target
        - hibernate.target
        - hybrid-sleep.target
        - suspend-then-hibernate.target

    - name: Ensure KDE power management settings prevent sleep
      copy:
        dest: /etc/xdg/autostart/disable-sleep.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=xset -dpms; xset s off
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_US]=Disable Sleep
          Name=Disable Sleep
          Comment=Prevents sleep and screen blanking

    - name: Ensure systemd prevents sleep when lid is closed
      lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^#?HandleLidSwitch='
        line: 'HandleLidSwitch=ignore'

    - name: Restart systemd-logind to apply lid switch settings
      systemd:
        name: systemd-logind
        state: restarted

  handlers:
    - name: Regenerate Initramfs
      command: mkinitcpio -P
    - name: Update GRUB
      command: grub-mkconfig -o /boot/grub/grub.cfg
